### ISSUE TITLE
Bugs: hide and seek

### ISSUE THREAD

**Issue by ab-noori** [AbdusSattar-70/portfolio#37]
Hi @AbdusSattar-70,
I have checked your repository, there is a bug on your localStorage.js in line 13: it is a syntax error --missing parenthesis and semicolon. please check and should fix it .

![screenshot_2023-02-11_235058](https://user-images.githubusercontent.com/111179533/218273942-29ed639b-1f1c-4a48-90b3-477733c700ed.png)

**Comment by AbdusSattar-70** [comment]
Hello @ab-noori, Thanks for investing time in my repo to check Bug. Resolved #37
