### ISSUE TITLE
Bugs: hide-and-seek

### ISSUE THREAD

**Issue by RHK-MICROVERSE** [AbdusSattar-70/portfolio#39]
Hello @AbdusSattar-70 
I have reviewed your repository related to the local-storage task and found a bug there in line number 16 which required the variable to be added.

![Bug_Issue](https://user-images.githubusercontent.com/36616717/224472255-432c5a98-cfb6-447a-85ac-8346002c2d7a.png)

**Comment by AbdusSattar-70** [comment]
Hello @RHK-MICROVERSE, 
Thank you for reviewing for giving me a good suggestion. I have solved issue #39
